package advising;

public class User {
    private String name;
    private String username;
    private String password;
    private String userType;


    public UserLoginInfo(String username, String password) {

    }

    public boolean classLookup(String class) {

        return true;
    }

    public boolean loginInput(String username, String password) {

        return true;
    }

    public void loginStudent() {

    }
    public void loginAdmin() {
        
    }
    public void loginAdvisor() {
        
    }

}